module.exports.default = function (api) {
  return new Promise((resolve, reject) => {
    console.log("List of available commands and subcommands:")

    console.log('\nAuthentication and mode')
    console.log('  cm auth demo - activate demo mode')
    console.log('  cm auth live - activate live mode')
    console.log('  cm auth login - login using your credentials')
    console.log('\nMarket data')
    console.log('  cm market list - list available markets (pairs)')
    console.log('  cm market chart - draw a market chart')
    console.log('  cm market trades - list recent market trades')
    console.log('  cm market book - display market order book')
    console.log('\nTrade platform')
    console.log('  cm trade balance - list your balances')
    console.log('  cm trade open - list open orders')
    console.log('  cm trade history - list filled orders')
    console.log('  cm trade buy - place a buy order')
    console.log('  cm trade sell - place a sell order')
    console.log('  cm trade mbuy - place a multi buy (iceberg) order')
    console.log('  cm trade msell - place a multi sell (iceberg) order')
    console.log('  cm trade cancel - cancel a single order using order id')
    console.log('  cm trade mcancel - cancel multiple orders using criteria')
    console.log('\nMargin platform')
    console.log('  cm margin balance - list your balances and update your collateral')
    console.log('  cm margin open - list open orders')
    console.log('  cm margin history - list filled orders')
    console.log('  cm margin buy - place a buy order')
    console.log('  cm margin sell - place a sell order')
    console.log('  cm margin mbuy - place a multi buy (iceberg) order')
    console.log('  cm margin msell - place a multi sell (iceberg) order')
    console.log('  cm margin cancel - cancel a single order using order id')
    console.log('  cm margin mcancel - cancel multiple orders using criteria')
    console.log('\nCommand module')
    console.log('  cm cmd list - list all stored commands')
    console.log('  cm cmd store - store a new command')
    console.log('  cm cmd del - delete a stored command')
    console.log('  cm cmd run - run a stored command')

    console.log('\nTo show detailed syntax for each command use the following format:')
    console.log('  cm <command> <subcommand> ?')
    console.log('  example: cm trade mbuy ?')

    console.log('\nCheck online docs for more info: https://github.com/u2ros/coinmetro-cli')

    resolve()
  })
}